version: 0.2

phases:
  pre_build:
    commands:
      - cd frontend && npm install
  build:
    commands:
      - npm run test
      - npm run lint
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: frontend/build