version: 0.2

phases:
  pre_build:
    commands:
      - cd websocket
      - npm install -g serverless
      - pip3 install black
      - npm install
      - pip3 install -r python-packages.txt -t ./lib/python
      - cd ../
      - cd frontend
      - npm install
      - cd ../
  build:
    commands:
      - cd websocket
      - black . --check --exclude '(/lib/*|/node_modules/*)'
      - python3 -m unittest discover tests
      - sls deploy
      - cd ../
      - cd frontend
      - npm run lint
      - npm run test
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: frontend/build