service: poker
org: edwardhorsey
app: poker

custom:
  currentStage: ${opt:stage, self:provider.stage}
  lambdaRunTime: python3.8
  pokerSingleTable: pokerSingleTable-${self:custom.currentStage}

provider:
  name: aws
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
  runtime: ${self:custom.lambdaRunTime}
  versionFunctions: false
  region: eu-west-1
  timeout: 29

plugins:
  - serverless-dotenv-plugin
  - serverless-pseudo-parameters
  - serverless-offline
package:
  individually: true
  exclude:
    - "lib/**"
    - "node_modules/**"

layers:
  pythonPackageLayer:
    path: lib
    name: Python-Package-layer
    description: Python Package layer
    compatibleRuntimes:
      - ${self:custom.lambdaRunTime}

functions:
  connectHandler:
    handler: connect_handler.handle
    events:
      - websocket: $connect
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      POKER_TABLE_NAME: ${self:custom.pokerSingleTable}

  disconnectHandler:
    handler: disconnect_handler.handle
    events:
      - websocket: $disconnect
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      POKER_TABLE_NAME: ${self:custom.pokerSingleTable}

  gameActionHandler:
    handler: game_action_handler.handle
    events:
      - websocket:
          route: onGameAction
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      POKER_TABLE_NAME: ${self:custom.pokerSingleTable}
      WEBSOCKET_AWS_COGNITO_APP_CLIENT_ID: ${param:WEBSOCKET_AWS_COGNITO_APP_CLIENT_ID}
      WEBSOCKET_AWS_COGNITO_APP_REDIRECT_URI: ${param:WEBSOCKET_AWS_COGNITO_APP_REDIRECT_URI}
      WEBSOCKET_AWS_COGNITO_APP_URL: ${param:WEBSOCKET_AWS_COGNITO_APP_URL}
      WEBSOCKET_AWS_COGNITO_USERPOOL_ID: ${param:WEBSOCKET_AWS_COGNITO_USERPOOL_ID}

resources:
  Resources:
    pokerSingleTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.pokerSingleTable}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: userTokenPK
            AttributeType: S
          - AttributeName: userTokenSK
            AttributeType: S
          - AttributeName: connectionIdPK
            AttributeType: S
          - AttributeName: connectionIdSK
            AttributeType: S
          - AttributeName: gameIdPK
            AttributeType: S
          - AttributeName: gameIdSK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
        - IndexName: userToken
          KeySchema:
          - AttributeName: userTokenPK
            KeyType: HASH
          - AttributeName: userTokenSK
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: connectionId
          KeySchema:
          - AttributeName: connectionIdPK
            KeyType: HASH
          - AttributeName: connectionIdSK
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: gameId
          KeySchema:
          - AttributeName: gameIdPK
            KeyType: HASH
          - AttributeName: gameIdSK
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true