service: poker
org: edwardhorsey
app: poker

custom:
  currentStage: ${opt:stage, self:provider.stage}
  lambdaRunTime: python3.8
  pokerConnections: pokerConnections-${self:custom.currentStage}
  pokerGames: pokerGames-${self:custom.currentStage}
  pokerPastGames: pokerPastGames-${self:custom.currentStage}

provider:
  name: aws
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
  runtime: ${self:custom.lambdaRunTime}
  versionFunctions: false
  region: eu-west-1
  timeout: 29

plugins:
  - serverless-pseudo-parameters
  - serverless-offline
package:
  individually: true
  exclude:
    - "lib/**"
    - "node_modules/**"

layers:
  pythonPackageLayer:
    path: lib
    name: Python-Package-layer
    description: Python Package layer
    compatibleRuntimes:
      - ${self:custom.lambdaRunTime}

functions:
  connectHandler:
    handler: connect_handler.handle
    events:
      - websocket: $connect
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      POKER_CONNECTIONS_TABLE_NAME: ${self:custom.pokerConnections}

  disconnectHandler:
    handler: disconnect_handler.handle
    events:
      - websocket: $disconnect
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      POKER_CONNECTIONS_TABLE_NAME: ${self:custom.pokerConnections}

  gameActionHandler:
    handler: game_action_handler.handle
    events:
      - websocket:
          route: onGameAction
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      POKER_CONNECTIONS_TABLE_NAME: ${self:custom.pokerConnections}
      POKER_GAMES_CONNECTIONS_TABLE_NAME: ${self:custom.pokerGames}
      POKER_PAST_GAMES_CONNECTIONS_TABLE_NAME: ${self:custom.pokerPastGames}

resources:
  Resources:
    pokerConnectionsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.pokerConnections}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true

    pokerGamesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.pokerGames}
        AttributeDefinitions:
          - AttributeName: gameId
            AttributeType: N
        KeySchema:
          - AttributeName: gameId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true

    pokerPastGamesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.pokerPastGames}
        AttributeDefinitions:
          - AttributeName: gameId
            AttributeType: N
        KeySchema:
          - AttributeName: gameId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true